# Neurons and Layers

In [4]:
!python --version

Python 3.12.3


In [7]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.activations import sigmoid
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy

In [8]:

X_train = np.array([[1.0], [2.0]], dtype=np.float32)           #(size in 1000 square feet)
Y_train = np.array([[300.0], [500.0]], dtype=np.float32)       #(price in 1000s of dollars)

print(X_train)
print(Y_train)

[[1.]
 [2.]]
[[300.]
 [500.]]


In [18]:
linear_layer = Dense(units=1, activation='linear')
print(linear_layer)
print(linear_layer.get_weights())
print(X_train[0].reshape(-1, 1))

a1 = linear_layer(X_train[0].reshape(1, 1))
print(a1)

<Dense name=dense_7, built=False>
[]
[[1.]]
tf.Tensor([[-1.2851154]], shape=(1, 1), dtype=float32)


In [19]:
w,b = linear_layer.get_weights()
print(f"w: {w}, b: {b}")

w: [[-1.2851154]], b: [0.]


In [20]:
set_w = np.array([[200]])
set_b = np.array([100])

# set_weights takes a list of numpy arrays
linear_layer.set_weights([set_w, set_b])
print(linear_layer.get_weights())

[array([[200.]], dtype=float32), array([100.], dtype=float32)]


In [21]:
a1 = linear_layer(X_train[0].reshape(1,1))
print(a1)
alin = np.dot(set_w,X_train[0].reshape(1,1)) + set_b
print(alin)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[[300.]]


In [22]:
prediction_tf = linear_layer(X_train)

In [23]:
print(prediction_tf)

tf.Tensor(
[[300.]
 [500.]], shape=(2, 1), dtype=float32)


In [24]:

X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

In [26]:
pos = Y_train == 1
neg = Y_train == 0
print(pos)
X_train[pos]

[[False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]]


array([3., 4., 5.], dtype=float32)

In [28]:
model = Sequential(
    [
        Dense(1, activation='sigmoid', name='L1'),
    ]
)


In [29]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
logistic_layer = model.get_layer('L1')
w,b = logistic_layer.get_weights()
print(f"w: {w}, b: {b}")
print(w.shape, b.shape)

w: [[1.129316]], b: [0.]
(1, 1) (1,)


In [32]:

set_w = np.array([[2]])
set_b = np.array([-4.5])
# set_weights takes a list of numpy arrays
logistic_layer.set_weights([set_w, set_b])
print(logistic_layer.get_weights())

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]


In [33]:
a1 = model.predict(X_train[0].reshape(1,1))
print(a1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[[0.01098694]]
