## Vector
向量化

In [1]:
!python --version

Python 3.12.3


In [2]:
import numpy as np
import time

In [6]:

# define a vector
a = np.zeros(5); print(f"a = {a} a.shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((6,)); print(f"a = {a} a.shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"a = {a} a.shape = {a.shape}, a data type = {a.dtype}")

a = [0. 0. 0. 0. 0.] a.shape = (5,), a data type = float64
a = [0. 0. 0. 0. 0. 0.] a.shape = (6,), a data type = float64
a = [0.3428553  0.46602892 0.63715795 0.27056769] a.shape = (4,), a data type = float64


## Operations on Vectors

In [8]:
a = np.arange(10); print(f"a = {a} a.shape = {a.shape}, a data type = {a.dtype}")

print(f"access last element: {a[-1]}")

a = [0 1 2 3 4 5 6 7 8 9] a.shape = (10,), a data type = int64
access last element: 9


### Slicing

In [15]:
print(a)
c = a[2:7:1]; print("a[2:7:1] =", c)
c = a[2:7:2]; print("a[2:7:2] =", c)
c = a[3:]; print("a[3:]=", c)
c = a[:3]; print("a[:3] =", c)
c = a[:] ; print("a[:] =", c)

[0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:]= [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


### Single Vector operations

In [21]:
a = np.array([1,2,3,4]); print(a)
b = -a; print(f"b = -a; b = {b}")
b = np.sum(a); print("b = np.sum(a) =", b)
b = np.mean(a); print("b = np.mean(a) =", b)
b = a ** 2; print("b = a ** 2 = ", b)

[1 2 3 4]
b = -a; b = [-1 -2 -3 -4]
b = np.sum(a) = 10
b = np.mean(a) = 2.5
b = a ** 2 =  [ 1  4  9 16]


### Vector element-wise operations


$$
a + b = \sum\limits_{i = 0}^{n-1} a_i + b_i
$$

In [23]:
a = np.array([1,2,3,4]); print(a)
b = np.array([-1,-2,3,4]); print(b)
print(f"a + b = {a + b}")

c = 5*a; print(f"c = 5*a = {c}")

[1 2 3 4]
[-1 -2  3  4]
a + b = [0 0 6 8]
c = 5*a = [ 5 10 15 20]


In [25]:
def vector_dot(v1, v2):
    
    x = 0
    for i in range(v1.shape[0]):
        x = x + v1[i] * v2[i]
    return x

a = np.array([1,2,3,4]); print(a)
b = np.array([-1,4,3,2]); print(b)

print("vector_dot(a,b) =", vector_dot(a,b))
print("np.dot(a,b) =", np.dot(a,b))

[1 2 3 4]
[-1  4  3  2]
vector_dot(a,b) = 24
np.dot(a,b) = 24


## Matrix


In [28]:
a = np.zeros((1,5)); print(f"a = {a} a.shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((2,5)); print(f"a = {a} a.shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample((2,2)); print(f"a = {a} a.shape = {a.shape}, a data type = {a.dtype}")

a = [[0. 0. 0. 0. 0.]] a.shape = (1, 5), a data type = float64
a = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] a.shape = (2, 5), a data type = float64
a = [[0.94568602 0.65776632]
 [0.43173139 0.20609544]] a.shape = (2, 2), a data type = float64


### Operations on Matrices

In [35]:
a = np.arange(6).reshape(-1, 2); print(f"a = {a} a.shape = {a.shape}, a data type = {a.dtype}")

print(f"access a[2,1] = {a[2,1]}, a[2,1] shape = {a[2,1].shape}, a[2,1] dtype = {a[2,1].dtype}")

print(f"access row a[2] = {a[2]}, a[2] shape = {a[2].shape}, type(a[2]) = {type(a[2])}")

a = [[0 1]
 [2 3]
 [4 5]] a.shape = (3, 2), a data type = int64
access a[2,1] = 5, a[2,1] shape = (), a[2,1] dtype = int64
access row a[2] = [4 5], a[2] shape = (2,), type(a[2]) = <class 'numpy.ndarray'>
